name: 'send daily weather'
on:
  push:
  schedule:
    - cron: '0 23 * * *'

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Get weathers
        run: |
          bash ./get-weather.sh Taiyuan
          bash ./get-weather.sh Nanchang
          bash ./get-weather.sh
      - name: send to vimily
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: '每日天气 今天也要好好减肥!'
          body: file://result-Nanchang.html
          to: 1518033321@qq.com
          from: '你的小奶狗的每日天气服务'
          content_type: text/html
      - name: send to myself
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: '每日天气'
          body: file://result-Taiyuan.html
          to: me@anco.fun,xunbinbin@hotmail.com,song.tian.shi@hotmail.com
          from: '每日天气服务'
          content_type: text/html
